Update [Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md
Adding the missing advanced_vpn_settings block which causes the error below when running terraform validate.
The root cause of the issue is the "settings.connectivity.tf " section in the document is not up to date with the latest version of variables.tf which is in the root folder of the repo.
"
 Error: Invalid value for module argument
│ 
│   on main.tf line 27, in module "enterprise_scale":
│   27:   configure_connectivity_resources = local.configure_connectivity_resources
│ 
│ The given value is not suitable for child module variable
│ "configure_connectivity_resources" defined at
│ .terraform/modules/enterprise_scale/variables.tf:203,1-44: attribute
│ "settings": attribute "hub_networks": element 0: attribute "config":
│ attribute "virtual_network_gateway": attribute "config": attribute
│ "advanced_vpn_settings" is required
"